# =============================================================================
# ODOO LOCAL DEVELOPMENT
# =============================================================================
#
# DESCRIPTION:
#   Deploy Odoo 14 for local development and testing
#
# REQUIREMENTS:
#   - Docker & Docker Compose installed
#   - .env file configured
#   - secrets/pg_password.txt with database password
#
# ACCESS:
#   - Odoo: http://localhost:8069
#
# NOTES:
#   - No HTTPS - for development/testing only
#   - Do not use in production
#
# =============================================================================

services:
  odoo-web:
    container_name: odoo-web
    image: odoo:14
    depends_on:
      odoo-db:
        condition: service_healthy
    ports:
      - "8069:8069"
    env_file:
      - .env
    environment:
      - USER=${USER}
      - HOST=${HOST}
      - PASSWORD_FILE=/run/secrets/pg_password
    secrets:
      - pg_password
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    networks:
      - odoo
    restart: unless-stopped

  odoo-db:
    container_name: odoo-db
    image: postgres:14
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PASSWORD_FILE=/run/secrets/pg_password
    secrets:
      - pg_password
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - odoo
    restart: unless-stopped

volumes:
  odoo-web-data:
  odoo-db-data:

networks:
  odoo:
    driver: bridge

secrets:
  pg_password:
    file: ./secrets/pg_password.txt