# =============================================================================
# ODOO WITH NGINX REVERSE PROXY
# =============================================================================
#
# DESCRIPTION:
#   Deploy Odoo 14 with Nginx as reverse proxy using self-signed SSL
#
# REQUIREMENTS:
#   - Docker & Docker Compose installed
#   - .env file configured
#   - secrets/pg_password.txt with database password
#   - SSL certificates in config/ directory:
#       openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
#           -keyout config/nginx.key -out config/nginx.crt \
#           -subj "/CN=localhost"
#
# ACCESS:
#   - Odoo: https://localhost or https://your-server-ip
#
# NOTES:
#   - Uses self-signed certificate (browser will show security warning)
#   - For production, replace with valid SSL certificate
#
# =============================================================================

services:
  odoo-web:
    container_name: odoo-web
    image: odoo:14
    depends_on:
      odoo-db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - USER=${USER}
      - HOST=${HOST}
      - PASSWORD_FILE=/run/secrets/pg_password
    secrets:
      - pg_password
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    networks:
      - odoo
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx-ssl.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx.crt:/etc/nginx/nginx.crt:ro
      - ./config/nginx.key:/etc/nginx/nginx.key:ro
    depends_on:
      - odoo-web
    networks:
      - odoo
    restart: unless-stopped

  odoo-db:
    container_name: odoo-db
    image: postgres:14
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PASSWORD_FILE=/run/secrets/pg_password
    secrets:
      - pg_password
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - odoo
    restart: unless-stopped

volumes:
  odoo-web-data:
  odoo-db-data:

networks:
  odoo:
    driver: bridge

secrets:
  pg_password:
    file: ./secrets/pg_password.txt
